/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#00714d",
        "outline-variant": "#c7c4d8",
        "inverse-on-surface": "#eef0ff",
        "surface-container": "#eaedff",
        "on-error-container": "#93000a",
        "primary": "#3525cd",
        "on-primary-fixed-variant": "#3323cc",
        "on-tertiary": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-surface": "#131b2e",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-fixed": "#0f0069",
        "surface-container-low": "#f2f3ff",
        "primary-fixed-dim": "#c3c0ff",
        "surface-dim": "#d2d9f4",
        "inverse-surface": "#283044",
        "on-background": "#131b2e",
        "surface": "#faf8ff",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "surface-variant": "#dae2fd",
        "tertiary": "#684000",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#6cf8bb",
        "tertiary-container": "#885500",
        "on-secondary-fixed-variant": "#005236",
        "error": "#ba1a1a",
        "primary-container": "#4f46e5",
        "on-secondary-fixed": "#002113",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-tint": "#4d44e3",
        "on-tertiary-container": "#ffd4a4",
        "background": "#faf8ff",
        "error-container": "#ffdad6",
        "surface-container-highest": "#dae2fd",
        "on-secondary": "#ffffff",
        "outline": "#777587",
        "on-primary-container": "#dad7ff",
        "surface-container-high": "#e2e7ff",
        "on-surface-variant": "#464555",
        "primary-fixed": "#e2dfff",
        "secondary-fixed": "#6ffbbe",
        "secondary": "#006c49",
        "inverse-primary": "#c3c0ff",
        "on-tertiary-fixed": "#2a1700"
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
        heading: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px"
      }
    }
  },
  plugins: [],
}
